// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var connection, consign, express, mysql;

  express = require("express");

  mysql = require("mysql");

  consign = require("consign");

  const app = express();

  const router = express.Router();

  connection = mysql.createConnection({
    host: 'localhost',
    port: '3306',
    user: 'linkitAdmin',
    password: 'linkitAdmin',
    database: 'linkit'
  });

  connection.connect(function(err) {
    if (err) {
      return console.error('error connecting: ' + err.stack);
    }
    console.log('connected as id ' + connection.threadId);
    app.listen(3000, function() {
      console.log('server listening on port 3000');
    });
  });

  app.connection = connection;

  consign({
    verbose: false
  }).include("libs/middlewares.js").include("routes").into(app);

  module.exports = app;

}).call(this);
