// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(app) {
    app.get("/", function(req, res) {
      return res.json({
        status: "Linkit Node Server"
      });
    });
    app.get("/product", function(req, res) {
      app.connection.query('SELECT * FROM products', [], function(err, results, fields) {
        if (err) {
          return console.error(err.stack);
        }
        res.send(results);
      });
    });
    app.get("/product/:id", function(req, res) {
      app.connection.query('SELECT * FROM products WHERE id = ?', [req.params.id], function(err, results, fields) {
        if (err) {
          return console.error(err.stack);
        }
        res.send(results);
      });
    });
    app.post("/product", function(req, res) {
      app.connection.query('INSERT INTO products (name,spec,stat,cost,sell,amnt) VALUES (?,?,?,?,?,?)', [req.body.name, req.body.spec, req.body.stat, req.body.cost, req.body.sell, req.body.amnt], function(err, results, fields) {
        if (err) {
          return console.error(err.stack);
        }
        res.send(results);
      });
    });
    app.put("/product", function(req, res) {
      app.connection.query('UPDATE products SET name = ?, spec = ?, stat = ?, cost = ?, sell = ?, amnt = ? WHERE id = ?', [req.body.name, req.body.spec, req.body.stat, req.body.cost, req.body.sell, req.body.amnt, req.body.id], function(err, results, fields) {
        if (err) {
          return console.error(err.stack);
        }
        res.send(results);
      });
    });
    return app["delete"]("/products", function(req, res) {
      app.connection.query('DELETE FROM products WHERE id = ?', [req.body.id], function(err, results, fields) {
        if (err) {
          return console.error(err.stack);
        }
        res.send(results);
      });
    });
  };

}).call(this);
