// Generated by CoffeeScript 1.9.3
(function() {
  var bodyParser, cors, express;

  bodyParser = require('body-parser');

  express = require('express');

  cors = require('cors');


  /*
  morgan      = require 'morgan'              //logger
  compression = require 'compression'         //compresses http for performance
  helmet      = require 'helmet'              //HTTP protection
  logger      = require './logger.js'         //logger
   */

  module.exports = function(app) {

    /*set port */
    app.set('port', 3000);

    /*JSON Formatting */
    app.set('json spaces', 4);

    /*CORS Support */
    app.use(cors({
      origin: ["http://localhost:8080"],
      methods: ["GET", "POST", "PUT", "DELETE"],
      allowedHeaders: ["Content-Type", "Authorization"]
    }));

    /*allows request body to be read */
    app.use(bodyParser.urlencoded({
      extended: true

      /*parses JSON data from body */
    }));
    app.use(bodyParser.json());

    /*app.use do app.auth.initialize       //for passport middleware */
    app.use(function(req, res, next) {
      delete req.body.id;
      next();
    });

    /*app.use express.static "public"      //allows access to static resources */
  };

}).call(this);
